// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuIPpgY3mRrRLCLT0Hq5d6Rwp8BqxrfOg',
    appId: '1:383332243396:web:c1b8f8d51852681b25f691',
    messagingSenderId: '383332243396',
    projectId: 'cancionero-7cd85',
    authDomain: 'cancionero-7cd85.firebaseapp.com',
    storageBucket: 'cancionero-7cd85.firebasestorage.app',
    measurementId: 'G-5RXLT9SXRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdRgVyXSCXK6LhksTHJ0_kdQApnRB6V9E',
    appId: '1:383332243396:android:5e13d66450cb9fea25f691',
    messagingSenderId: '383332243396',
    projectId: 'cancionero-7cd85',
    storageBucket: 'cancionero-7cd85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Ny5ckt74wbBVi2r_SmfXG27XGS-c3fI',
    appId: '1:383332243396:ios:8180c3bc5282fcb525f691',
    messagingSenderId: '383332243396',
    projectId: 'cancionero-7cd85',
    storageBucket: 'cancionero-7cd85.firebasestorage.app',
    iosClientId: '383332243396-n0fv7db011fmmjjdgkqt3oj1782aml3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cancionero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Ny5ckt74wbBVi2r_SmfXG27XGS-c3fI',
    appId: '1:383332243396:ios:8180c3bc5282fcb525f691',
    messagingSenderId: '383332243396',
    projectId: 'cancionero-7cd85',
    storageBucket: 'cancionero-7cd85.firebasestorage.app',
    iosClientId: '383332243396-n0fv7db011fmmjjdgkqt3oj1782aml3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cancionero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuIPpgY3mRrRLCLT0Hq5d6Rwp8BqxrfOg',
    appId: '1:383332243396:web:85be3070a84009fa25f691',
    messagingSenderId: '383332243396',
    projectId: 'cancionero-7cd85',
    authDomain: 'cancionero-7cd85.firebaseapp.com',
    storageBucket: 'cancionero-7cd85.firebasestorage.app',
    measurementId: 'G-C1048MZG06',
  );
}
